[package]
name = "weather-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.199", features = ["derive"]}
reqwest = {version = "0.12.4", features = ["blocking", "json"]}
serde_json = "1.0"
